# Generated by Django 4.0.4 on 2022-06-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_contactinfo_id_userprofileinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='vehiculated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
